Added old containers upgrade support in the XFS disk isolator.
apache/mesos pull request #463
Opened 2024-01-16 18:37 UTC by DevinLeamy

Currently containers that were created prior to enabling the XFS disk
isolator were simply ignored by it. With this change the isolator
assigns XFS project IDs to sandboxes of the old containers upon recovery
and manages them.

2024-01-16 21:09 UTC, bmahler requested changes

2024-01-16 21:09 UTC, bmahler commented on src/tests/containerizer/xfs_quota_tests.cpp
> +  }
Looks like this can be simplified?

```
  while (!os::exists(path) && timer.elapsed() < duration) {
    os::sleep(Milliseconds(50));
  }
```

2024-01-16 21:09 UTC, bmahler commented on src/slave/containerizer/mesos/isolators/xfs/disk.cpp
> +      return Failure("Failed to assign project ID, range exhausted");
"Failed to assign project to sandbox <sandbox>: Failed to obtain next project ID: range exhausted" (wrap lines at 80 though, so split onto multiple lines).

2024-01-16 21:09 UTC, bmahler commented on src/slave/containerizer/mesos/isolators/xfs/disk.cpp
> +  list<string> unmanaged;
we default to vector unless list is needed for e.g. O(1) insertion, so: s/list/vector/

2024-01-16 23:04 UTC, DevinLeamy commented on src/tests/containerizer/xfs_quota_tests.cpp
> +  }
```cpp
 while (!os::exists(path) && timer.elapsed() <= duration) {
    os::sleep(Milliseconds(50));
  }
  ```

2024-01-17 17:45 UTC, bmahler requested changes

2024-01-17 17:45 UTC, bmahler commented on src/tests/containerizer/xfs_quota_tests.cpp
> +  }
you've accidentally kept the original loop here too?

2024-01-17 17:45 UTC, bmahler commented on src/slave/containerizer/mesos/isolators/xfs/disk.cpp
> +        "next project ID: range exhausted");
leading space needed here, and prefix with + on the next line:

```
+ " next project ID: range exhausted"
```

2024-01-19 04:47 UTC, merged